// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_nested.proto

public final class AddressNested {
  private AddressNested() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string building_name = 1;</code>
     */
    java.lang.String getBuildingName();
    /**
     * <code>string building_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getBuildingNameBytes();

    /**
     * <code>int32 bulding_number = 2;</code>
     */
    int getBuldingNumber();

    /**
     * <code>.Building.Street street = 3;</code>
     */
    boolean hasStreet();
    /**
     * <code>.Building.Street street = 3;</code>
     */
    AddressNested.Building.Street getStreet();
    /**
     * <code>.Building.Street street = 3;</code>
     */
    AddressNested.Building.StreetOrBuilder getStreetOrBuilder();
  }
  /**
   * Protobuf type {@code Building}
   */
  public  static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
      buildingName_ = "";
      buldingNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              buildingName_ = s;
              break;
            }
            case 16: {

              buldingNumber_ = input.readInt32();
              break;
            }
            case 26: {
              AddressNested.Building.Street.Builder subBuilder = null;
              if (street_ != null) {
                subBuilder = street_.toBuilder();
              }
              street_ = input.readMessage(AddressNested.Building.Street.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(street_);
                street_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AddressNested.internal_static_Building_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AddressNested.internal_static_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddressNested.Building.class, AddressNested.Building.Builder.class);
    }

    public interface StreetOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Building.Street)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>.Building.Street.City city = 2;</code>
       */
      boolean hasCity();
      /**
       * <code>.Building.Street.City city = 2;</code>
       */
      AddressNested.Building.Street.City getCity();
      /**
       * <code>.Building.Street.City city = 2;</code>
       */
      AddressNested.Building.Street.CityOrBuilder getCityOrBuilder();
    }
    /**
     * Protobuf type {@code Building.Street}
     */
    public  static final class Street extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Building.Street)
        StreetOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Street.newBuilder() to construct.
      private Street(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Street() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Street(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                AddressNested.Building.Street.City.Builder subBuilder = null;
                if (city_ != null) {
                  subBuilder = city_.toBuilder();
                }
                city_ = input.readMessage(AddressNested.Building.Street.City.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(city_);
                  city_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AddressNested.internal_static_Building_Street_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AddressNested.internal_static_Building_Street_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddressNested.Building.Street.class, AddressNested.Building.Street.Builder.class);
      }

      public interface CityOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Building.Street.City)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 1;</code>
         */
        com.google.protobuf.ByteString
            getNameBytes();

        /**
         * <code>string ZIP_Code = 2;</code>
         */
        java.lang.String getZIPCode();
        /**
         * <code>string ZIP_Code = 2;</code>
         */
        com.google.protobuf.ByteString
            getZIPCodeBytes();

        /**
         * <code>string country = 3;</code>
         */
        java.lang.String getCountry();
        /**
         * <code>string country = 3;</code>
         */
        com.google.protobuf.ByteString
            getCountryBytes();
      }
      /**
       * Protobuf type {@code Building.Street.City}
       */
      public  static final class City extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Building.Street.City)
          CityOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use City.newBuilder() to construct.
        private City(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private City() {
          name_ = "";
          zIPCode_ = "";
          country_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        private City(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          this();
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 18: {
                  java.lang.String s = input.readStringRequireUtf8();

                  zIPCode_ = s;
                  break;
                }
                case 26: {
                  java.lang.String s = input.readStringRequireUtf8();

                  country_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return AddressNested.internal_static_Building_Street_City_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return AddressNested.internal_static_Building_Street_City_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  AddressNested.Building.Street.City.class, AddressNested.Building.Street.City.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        public static final int ZIP_CODE_FIELD_NUMBER = 2;
        private volatile java.lang.Object zIPCode_;
        /**
         * <code>string ZIP_Code = 2;</code>
         */
        public java.lang.String getZIPCode() {
          java.lang.Object ref = zIPCode_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            zIPCode_ = s;
            return s;
          }
        }
        /**
         * <code>string ZIP_Code = 2;</code>
         */
        public com.google.protobuf.ByteString
            getZIPCodeBytes() {
          java.lang.Object ref = zIPCode_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            zIPCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        public static final int COUNTRY_FIELD_NUMBER = 3;
        private volatile java.lang.Object country_;
        /**
         * <code>string country = 3;</code>
         */
        public java.lang.String getCountry() {
          java.lang.Object ref = country_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            country_ = s;
            return s;
          }
        }
        /**
         * <code>string country = 3;</code>
         */
        public com.google.protobuf.ByteString
            getCountryBytes() {
          java.lang.Object ref = country_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
          }
          if (!getZIPCodeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, zIPCode_);
          }
          if (!getCountryBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, country_);
          }
          unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
          }
          if (!getZIPCodeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, zIPCode_);
          }
          if (!getCountryBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, country_);
          }
          size += unknownFields.getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof AddressNested.Building.Street.City)) {
            return super.equals(obj);
          }
          AddressNested.Building.Street.City other = (AddressNested.Building.Street.City) obj;

          boolean result = true;
          result = result && getName()
              .equals(other.getName());
          result = result && getZIPCode()
              .equals(other.getZIPCode());
          result = result && getCountry()
              .equals(other.getCountry());
          result = result && unknownFields.equals(other.unknownFields);
          return result;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          hash = (37 * hash) + ZIP_CODE_FIELD_NUMBER;
          hash = (53 * hash) + getZIPCode().hashCode();
          hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
          hash = (53 * hash) + getCountry().hashCode();
          hash = (29 * hash) + unknownFields.hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static AddressNested.Building.Street.City parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static AddressNested.Building.Street.City parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static AddressNested.Building.Street.City parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static AddressNested.Building.Street.City parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static AddressNested.Building.Street.City parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static AddressNested.Building.Street.City parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static AddressNested.Building.Street.City parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static AddressNested.Building.Street.City parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static AddressNested.Building.Street.City parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static AddressNested.Building.Street.City parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static AddressNested.Building.Street.City parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static AddressNested.Building.Street.City parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(AddressNested.Building.Street.City prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code Building.Street.City}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Building.Street.City)
            AddressNested.Building.Street.CityOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return AddressNested.internal_static_Building_Street_City_descriptor;
          }

          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return AddressNested.internal_static_Building_Street_City_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    AddressNested.Building.Street.City.class, AddressNested.Building.Street.City.Builder.class);
          }

          // Construct using AddressNested.Building.Street.City.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
          }
          public Builder clear() {
            super.clear();
            name_ = "";

            zIPCode_ = "";

            country_ = "";

            return this;
          }

          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return AddressNested.internal_static_Building_Street_City_descriptor;
          }

          public AddressNested.Building.Street.City getDefaultInstanceForType() {
            return AddressNested.Building.Street.City.getDefaultInstance();
          }

          public AddressNested.Building.Street.City build() {
            AddressNested.Building.Street.City result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public AddressNested.Building.Street.City buildPartial() {
            AddressNested.Building.Street.City result = new AddressNested.Building.Street.City(this);
            result.name_ = name_;
            result.zIPCode_ = zIPCode_;
            result.country_ = country_;
            onBuilt();
            return result;
          }

          public Builder clone() {
            return (Builder) super.clone();
          }
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.setField(field, value);
          }
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
          }
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
          }
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
          }
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
          }
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof AddressNested.Building.Street.City) {
              return mergeFrom((AddressNested.Building.Street.City)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(AddressNested.Building.Street.City other) {
            if (other == AddressNested.Building.Street.City.getDefaultInstance()) return this;
            if (!other.getName().isEmpty()) {
              name_ = other.name_;
              onChanged();
            }
            if (!other.getZIPCode().isEmpty()) {
              zIPCode_ = other.zIPCode_;
              onChanged();
            }
            if (!other.getCountry().isEmpty()) {
              country_ = other.country_;
              onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
          }

          public final boolean isInitialized() {
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            AddressNested.Building.Street.City parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (AddressNested.Building.Street.City) e.getUnfinishedMessage();
              throw e.unwrapIOException();
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }

          private java.lang.Object name_ = "";
          /**
           * <code>string name = 1;</code>
           */
          public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              name_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>string name = 1;</code>
           */
          public com.google.protobuf.ByteString
              getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              name_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder setName(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  
            name_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder clearName() {
            
            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
            
            name_ = value;
            onChanged();
            return this;
          }

          private java.lang.Object zIPCode_ = "";
          /**
           * <code>string ZIP_Code = 2;</code>
           */
          public java.lang.String getZIPCode() {
            java.lang.Object ref = zIPCode_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              zIPCode_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>string ZIP_Code = 2;</code>
           */
          public com.google.protobuf.ByteString
              getZIPCodeBytes() {
            java.lang.Object ref = zIPCode_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              zIPCode_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>string ZIP_Code = 2;</code>
           */
          public Builder setZIPCode(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  
            zIPCode_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>string ZIP_Code = 2;</code>
           */
          public Builder clearZIPCode() {
            
            zIPCode_ = getDefaultInstance().getZIPCode();
            onChanged();
            return this;
          }
          /**
           * <code>string ZIP_Code = 2;</code>
           */
          public Builder setZIPCodeBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
            
            zIPCode_ = value;
            onChanged();
            return this;
          }

          private java.lang.Object country_ = "";
          /**
           * <code>string country = 3;</code>
           */
          public java.lang.String getCountry() {
            java.lang.Object ref = country_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              country_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>string country = 3;</code>
           */
          public com.google.protobuf.ByteString
              getCountryBytes() {
            java.lang.Object ref = country_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              country_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>string country = 3;</code>
           */
          public Builder setCountry(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  
            country_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>string country = 3;</code>
           */
          public Builder clearCountry() {
            
            country_ = getDefaultInstance().getCountry();
            onChanged();
            return this;
          }
          /**
           * <code>string country = 3;</code>
           */
          public Builder setCountryBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
            
            country_ = value;
            onChanged();
            return this;
          }
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
          }

          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:Building.Street.City)
        }

        // @@protoc_insertion_point(class_scope:Building.Street.City)
        private static final AddressNested.Building.Street.City DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new AddressNested.Building.Street.City();
        }

        public static AddressNested.Building.Street.City getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<City>
            PARSER = new com.google.protobuf.AbstractParser<City>() {
          public City parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new City(input, extensionRegistry);
          }
        };

        public static com.google.protobuf.Parser<City> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<City> getParserForType() {
          return PARSER;
        }

        public AddressNested.Building.Street.City getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CITY_FIELD_NUMBER = 2;
      private AddressNested.Building.Street.City city_;
      /**
       * <code>.Building.Street.City city = 2;</code>
       */
      public boolean hasCity() {
        return city_ != null;
      }
      /**
       * <code>.Building.Street.City city = 2;</code>
       */
      public AddressNested.Building.Street.City getCity() {
        return city_ == null ? AddressNested.Building.Street.City.getDefaultInstance() : city_;
      }
      /**
       * <code>.Building.Street.City city = 2;</code>
       */
      public AddressNested.Building.Street.CityOrBuilder getCityOrBuilder() {
        return getCity();
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (city_ != null) {
          output.writeMessage(2, getCity());
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (city_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getCity());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof AddressNested.Building.Street)) {
          return super.equals(obj);
        }
        AddressNested.Building.Street other = (AddressNested.Building.Street) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && (hasCity() == other.hasCity());
        if (hasCity()) {
          result = result && getCity()
              .equals(other.getCity());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        if (hasCity()) {
          hash = (37 * hash) + CITY_FIELD_NUMBER;
          hash = (53 * hash) + getCity().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static AddressNested.Building.Street parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static AddressNested.Building.Street parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static AddressNested.Building.Street parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static AddressNested.Building.Street parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static AddressNested.Building.Street parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static AddressNested.Building.Street parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static AddressNested.Building.Street parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static AddressNested.Building.Street parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static AddressNested.Building.Street parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static AddressNested.Building.Street parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static AddressNested.Building.Street parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static AddressNested.Building.Street parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(AddressNested.Building.Street prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Building.Street}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Building.Street)
          AddressNested.Building.StreetOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return AddressNested.internal_static_Building_Street_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return AddressNested.internal_static_Building_Street_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  AddressNested.Building.Street.class, AddressNested.Building.Street.Builder.class);
        }

        // Construct using AddressNested.Building.Street.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          if (cityBuilder_ == null) {
            city_ = null;
          } else {
            city_ = null;
            cityBuilder_ = null;
          }
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return AddressNested.internal_static_Building_Street_descriptor;
        }

        public AddressNested.Building.Street getDefaultInstanceForType() {
          return AddressNested.Building.Street.getDefaultInstance();
        }

        public AddressNested.Building.Street build() {
          AddressNested.Building.Street result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public AddressNested.Building.Street buildPartial() {
          AddressNested.Building.Street result = new AddressNested.Building.Street(this);
          result.name_ = name_;
          if (cityBuilder_ == null) {
            result.city_ = city_;
          } else {
            result.city_ = cityBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof AddressNested.Building.Street) {
            return mergeFrom((AddressNested.Building.Street)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(AddressNested.Building.Street other) {
          if (other == AddressNested.Building.Street.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.hasCity()) {
            mergeCity(other.getCity());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          AddressNested.Building.Street parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (AddressNested.Building.Street) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private AddressNested.Building.Street.City city_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            AddressNested.Building.Street.City, AddressNested.Building.Street.City.Builder, AddressNested.Building.Street.CityOrBuilder> cityBuilder_;
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public boolean hasCity() {
          return cityBuilder_ != null || city_ != null;
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public AddressNested.Building.Street.City getCity() {
          if (cityBuilder_ == null) {
            return city_ == null ? AddressNested.Building.Street.City.getDefaultInstance() : city_;
          } else {
            return cityBuilder_.getMessage();
          }
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public Builder setCity(AddressNested.Building.Street.City value) {
          if (cityBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            city_ = value;
            onChanged();
          } else {
            cityBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public Builder setCity(
            AddressNested.Building.Street.City.Builder builderForValue) {
          if (cityBuilder_ == null) {
            city_ = builderForValue.build();
            onChanged();
          } else {
            cityBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public Builder mergeCity(AddressNested.Building.Street.City value) {
          if (cityBuilder_ == null) {
            if (city_ != null) {
              city_ =
                AddressNested.Building.Street.City.newBuilder(city_).mergeFrom(value).buildPartial();
            } else {
              city_ = value;
            }
            onChanged();
          } else {
            cityBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public Builder clearCity() {
          if (cityBuilder_ == null) {
            city_ = null;
            onChanged();
          } else {
            city_ = null;
            cityBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public AddressNested.Building.Street.City.Builder getCityBuilder() {
          
          onChanged();
          return getCityFieldBuilder().getBuilder();
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        public AddressNested.Building.Street.CityOrBuilder getCityOrBuilder() {
          if (cityBuilder_ != null) {
            return cityBuilder_.getMessageOrBuilder();
          } else {
            return city_ == null ?
                AddressNested.Building.Street.City.getDefaultInstance() : city_;
          }
        }
        /**
         * <code>.Building.Street.City city = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            AddressNested.Building.Street.City, AddressNested.Building.Street.City.Builder, AddressNested.Building.Street.CityOrBuilder> 
            getCityFieldBuilder() {
          if (cityBuilder_ == null) {
            cityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                AddressNested.Building.Street.City, AddressNested.Building.Street.City.Builder, AddressNested.Building.Street.CityOrBuilder>(
                    getCity(),
                    getParentForChildren(),
                    isClean());
            city_ = null;
          }
          return cityBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Building.Street)
      }

      // @@protoc_insertion_point(class_scope:Building.Street)
      private static final AddressNested.Building.Street DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new AddressNested.Building.Street();
      }

      public static AddressNested.Building.Street getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Street>
          PARSER = new com.google.protobuf.AbstractParser<Street>() {
        public Street parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Street(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Street> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Street> getParserForType() {
        return PARSER;
      }

      public AddressNested.Building.Street getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int BUILDING_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object buildingName_;
    /**
     * <code>string building_name = 1;</code>
     */
    public java.lang.String getBuildingName() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingName_ = s;
        return s;
      }
    }
    /**
     * <code>string building_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBuildingNameBytes() {
      java.lang.Object ref = buildingName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BULDING_NUMBER_FIELD_NUMBER = 2;
    private int buldingNumber_;
    /**
     * <code>int32 bulding_number = 2;</code>
     */
    public int getBuldingNumber() {
      return buldingNumber_;
    }

    public static final int STREET_FIELD_NUMBER = 3;
    private AddressNested.Building.Street street_;
    /**
     * <code>.Building.Street street = 3;</code>
     */
    public boolean hasStreet() {
      return street_ != null;
    }
    /**
     * <code>.Building.Street street = 3;</code>
     */
    public AddressNested.Building.Street getStreet() {
      return street_ == null ? AddressNested.Building.Street.getDefaultInstance() : street_;
    }
    /**
     * <code>.Building.Street street = 3;</code>
     */
    public AddressNested.Building.StreetOrBuilder getStreetOrBuilder() {
      return getStreet();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBuildingNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildingName_);
      }
      if (buldingNumber_ != 0) {
        output.writeInt32(2, buldingNumber_);
      }
      if (street_ != null) {
        output.writeMessage(3, getStreet());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBuildingNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildingName_);
      }
      if (buldingNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buldingNumber_);
      }
      if (street_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStreet());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AddressNested.Building)) {
        return super.equals(obj);
      }
      AddressNested.Building other = (AddressNested.Building) obj;

      boolean result = true;
      result = result && getBuildingName()
          .equals(other.getBuildingName());
      result = result && (getBuldingNumber()
          == other.getBuldingNumber());
      result = result && (hasStreet() == other.hasStreet());
      if (hasStreet()) {
        result = result && getStreet()
            .equals(other.getStreet());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDING_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingName().hashCode();
      hash = (37 * hash) + BULDING_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBuldingNumber();
      if (hasStreet()) {
        hash = (37 * hash) + STREET_FIELD_NUMBER;
        hash = (53 * hash) + getStreet().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AddressNested.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressNested.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressNested.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressNested.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressNested.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressNested.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressNested.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressNested.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressNested.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddressNested.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressNested.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressNested.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddressNested.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Building)
        AddressNested.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AddressNested.internal_static_Building_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AddressNested.internal_static_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddressNested.Building.class, AddressNested.Building.Builder.class);
      }

      // Construct using AddressNested.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        buildingName_ = "";

        buldingNumber_ = 0;

        if (streetBuilder_ == null) {
          street_ = null;
        } else {
          street_ = null;
          streetBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AddressNested.internal_static_Building_descriptor;
      }

      public AddressNested.Building getDefaultInstanceForType() {
        return AddressNested.Building.getDefaultInstance();
      }

      public AddressNested.Building build() {
        AddressNested.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AddressNested.Building buildPartial() {
        AddressNested.Building result = new AddressNested.Building(this);
        result.buildingName_ = buildingName_;
        result.buldingNumber_ = buldingNumber_;
        if (streetBuilder_ == null) {
          result.street_ = street_;
        } else {
          result.street_ = streetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddressNested.Building) {
          return mergeFrom((AddressNested.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddressNested.Building other) {
        if (other == AddressNested.Building.getDefaultInstance()) return this;
        if (!other.getBuildingName().isEmpty()) {
          buildingName_ = other.buildingName_;
          onChanged();
        }
        if (other.getBuldingNumber() != 0) {
          setBuldingNumber(other.getBuldingNumber());
        }
        if (other.hasStreet()) {
          mergeStreet(other.getStreet());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddressNested.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddressNested.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buildingName_ = "";
      /**
       * <code>string building_name = 1;</code>
       */
      public java.lang.String getBuildingName() {
        java.lang.Object ref = buildingName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string building_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBuildingNameBytes() {
        java.lang.Object ref = buildingName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string building_name = 1;</code>
       */
      public Builder setBuildingName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildingName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 1;</code>
       */
      public Builder clearBuildingName() {
        
        buildingName_ = getDefaultInstance().getBuildingName();
        onChanged();
        return this;
      }
      /**
       * <code>string building_name = 1;</code>
       */
      public Builder setBuildingNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildingName_ = value;
        onChanged();
        return this;
      }

      private int buldingNumber_ ;
      /**
       * <code>int32 bulding_number = 2;</code>
       */
      public int getBuldingNumber() {
        return buldingNumber_;
      }
      /**
       * <code>int32 bulding_number = 2;</code>
       */
      public Builder setBuldingNumber(int value) {
        
        buldingNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bulding_number = 2;</code>
       */
      public Builder clearBuldingNumber() {
        
        buldingNumber_ = 0;
        onChanged();
        return this;
      }

      private AddressNested.Building.Street street_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressNested.Building.Street, AddressNested.Building.Street.Builder, AddressNested.Building.StreetOrBuilder> streetBuilder_;
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public boolean hasStreet() {
        return streetBuilder_ != null || street_ != null;
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public AddressNested.Building.Street getStreet() {
        if (streetBuilder_ == null) {
          return street_ == null ? AddressNested.Building.Street.getDefaultInstance() : street_;
        } else {
          return streetBuilder_.getMessage();
        }
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public Builder setStreet(AddressNested.Building.Street value) {
        if (streetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          street_ = value;
          onChanged();
        } else {
          streetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public Builder setStreet(
          AddressNested.Building.Street.Builder builderForValue) {
        if (streetBuilder_ == null) {
          street_ = builderForValue.build();
          onChanged();
        } else {
          streetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public Builder mergeStreet(AddressNested.Building.Street value) {
        if (streetBuilder_ == null) {
          if (street_ != null) {
            street_ =
              AddressNested.Building.Street.newBuilder(street_).mergeFrom(value).buildPartial();
          } else {
            street_ = value;
          }
          onChanged();
        } else {
          streetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public Builder clearStreet() {
        if (streetBuilder_ == null) {
          street_ = null;
          onChanged();
        } else {
          street_ = null;
          streetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public AddressNested.Building.Street.Builder getStreetBuilder() {
        
        onChanged();
        return getStreetFieldBuilder().getBuilder();
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      public AddressNested.Building.StreetOrBuilder getStreetOrBuilder() {
        if (streetBuilder_ != null) {
          return streetBuilder_.getMessageOrBuilder();
        } else {
          return street_ == null ?
              AddressNested.Building.Street.getDefaultInstance() : street_;
        }
      }
      /**
       * <code>.Building.Street street = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressNested.Building.Street, AddressNested.Building.Street.Builder, AddressNested.Building.StreetOrBuilder> 
          getStreetFieldBuilder() {
        if (streetBuilder_ == null) {
          streetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AddressNested.Building.Street, AddressNested.Building.Street.Builder, AddressNested.Building.StreetOrBuilder>(
                  getStreet(),
                  getParentForChildren(),
                  isClean());
          street_ = null;
        }
        return streetBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Building)
    }

    // @@protoc_insertion_point(class_scope:Building)
    private static final AddressNested.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddressNested.Building();
    }

    public static AddressNested.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    public AddressNested.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Building_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Building_Street_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Building_Street_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Building_Street_City_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Building_Street_City_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024address_nested.proto\"\321\001\n\010Building\022\025\n\rb" +
      "uilding_name\030\001 \001(\t\022\026\n\016bulding_number\030\002 \001" +
      "(\005\022 \n\006street\030\003 \001(\0132\020.Building.Street\032t\n\006" +
      "Street\022\014\n\004name\030\001 \001(\t\022#\n\004city\030\002 \001(\0132\025.Bui" +
      "lding.Street.City\0327\n\004City\022\014\n\004name\030\001 \001(\t\022" +
      "\020\n\010ZIP_Code\030\002 \001(\t\022\017\n\007country\030\003 \001(\tb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Building_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Building_descriptor,
        new java.lang.String[] { "BuildingName", "BuldingNumber", "Street", });
    internal_static_Building_Street_descriptor =
      internal_static_Building_descriptor.getNestedTypes().get(0);
    internal_static_Building_Street_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Building_Street_descriptor,
        new java.lang.String[] { "Name", "City", });
    internal_static_Building_Street_City_descriptor =
      internal_static_Building_Street_descriptor.getNestedTypes().get(0);
    internal_static_Building_Street_City_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Building_Street_City_descriptor,
        new java.lang.String[] { "Name", "ZIPCode", "Country", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
