// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dayOfWeek.proto

public final class DayOfWeek {
  private DayOfWeek() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface dayOfWeekOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dayOfWeek)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dayOfWeek.Day day_of_Week = 1;</code>
     */
    int getDayOfWeekValue();
    /**
     * <code>.dayOfWeek.Day day_of_Week = 1;</code>
     */
    DayOfWeek.dayOfWeek.Day getDayOfWeek();
  }
  /**
   * Protobuf type {@code dayOfWeek}
   */
  public  static final class dayOfWeek extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dayOfWeek)
      dayOfWeekOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use dayOfWeek.newBuilder() to construct.
    private dayOfWeek(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private dayOfWeek() {
      dayOfWeek_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private dayOfWeek(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              dayOfWeek_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DayOfWeek.internal_static_dayOfWeek_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DayOfWeek.internal_static_dayOfWeek_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DayOfWeek.dayOfWeek.class, DayOfWeek.dayOfWeek.Builder.class);
    }

    /**
     * Protobuf enum {@code dayOfWeek.Day}
     */
    public enum Day
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNDEFINED = 0;</code>
       */
      UNDEFINED(0),
      /**
       * <code>MONDAY = 1;</code>
       */
      MONDAY(1),
      /**
       * <code>TUESDAY = 2;</code>
       */
      TUESDAY(2),
      /**
       * <code>WEDNESDAY = 3;</code>
       */
      WEDNESDAY(3),
      /**
       * <code>THURSDAY = 4;</code>
       */
      THURSDAY(4),
      /**
       * <code>FRIDAY = 5;</code>
       */
      FRIDAY(5),
      /**
       * <code>SATURDAY = 6;</code>
       */
      SATURDAY(6),
      /**
       * <code>SUNDAY = 7;</code>
       */
      SUNDAY(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNDEFINED = 0;</code>
       */
      public static final int UNDEFINED_VALUE = 0;
      /**
       * <code>MONDAY = 1;</code>
       */
      public static final int MONDAY_VALUE = 1;
      /**
       * <code>TUESDAY = 2;</code>
       */
      public static final int TUESDAY_VALUE = 2;
      /**
       * <code>WEDNESDAY = 3;</code>
       */
      public static final int WEDNESDAY_VALUE = 3;
      /**
       * <code>THURSDAY = 4;</code>
       */
      public static final int THURSDAY_VALUE = 4;
      /**
       * <code>FRIDAY = 5;</code>
       */
      public static final int FRIDAY_VALUE = 5;
      /**
       * <code>SATURDAY = 6;</code>
       */
      public static final int SATURDAY_VALUE = 6;
      /**
       * <code>SUNDAY = 7;</code>
       */
      public static final int SUNDAY_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Day valueOf(int value) {
        return forNumber(value);
      }

      public static Day forNumber(int value) {
        switch (value) {
          case 0: return UNDEFINED;
          case 1: return MONDAY;
          case 2: return TUESDAY;
          case 3: return WEDNESDAY;
          case 4: return THURSDAY;
          case 5: return FRIDAY;
          case 6: return SATURDAY;
          case 7: return SUNDAY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Day>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Day> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Day>() {
              public Day findValueByNumber(int number) {
                return Day.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DayOfWeek.dayOfWeek.getDescriptor().getEnumTypes().get(0);
      }

      private static final Day[] VALUES = values();

      public static Day valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Day(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dayOfWeek.Day)
    }

    public static final int DAY_OF_WEEK_FIELD_NUMBER = 1;
    private int dayOfWeek_;
    /**
     * <code>.dayOfWeek.Day day_of_Week = 1;</code>
     */
    public int getDayOfWeekValue() {
      return dayOfWeek_;
    }
    /**
     * <code>.dayOfWeek.Day day_of_Week = 1;</code>
     */
    public DayOfWeek.dayOfWeek.Day getDayOfWeek() {
      DayOfWeek.dayOfWeek.Day result = DayOfWeek.dayOfWeek.Day.valueOf(dayOfWeek_);
      return result == null ? DayOfWeek.dayOfWeek.Day.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dayOfWeek_ != DayOfWeek.dayOfWeek.Day.UNDEFINED.getNumber()) {
        output.writeEnum(1, dayOfWeek_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dayOfWeek_ != DayOfWeek.dayOfWeek.Day.UNDEFINED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dayOfWeek_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DayOfWeek.dayOfWeek)) {
        return super.equals(obj);
      }
      DayOfWeek.dayOfWeek other = (DayOfWeek.dayOfWeek) obj;

      boolean result = true;
      result = result && dayOfWeek_ == other.dayOfWeek_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DAY_OF_WEEK_FIELD_NUMBER;
      hash = (53 * hash) + dayOfWeek_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DayOfWeek.dayOfWeek parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DayOfWeek.dayOfWeek parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DayOfWeek.dayOfWeek parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DayOfWeek.dayOfWeek parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DayOfWeek.dayOfWeek parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DayOfWeek.dayOfWeek parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DayOfWeek.dayOfWeek prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dayOfWeek}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dayOfWeek)
        DayOfWeek.dayOfWeekOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DayOfWeek.internal_static_dayOfWeek_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DayOfWeek.internal_static_dayOfWeek_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DayOfWeek.dayOfWeek.class, DayOfWeek.dayOfWeek.Builder.class);
      }

      // Construct using DayOfWeek.dayOfWeek.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dayOfWeek_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DayOfWeek.internal_static_dayOfWeek_descriptor;
      }

      public DayOfWeek.dayOfWeek getDefaultInstanceForType() {
        return DayOfWeek.dayOfWeek.getDefaultInstance();
      }

      public DayOfWeek.dayOfWeek build() {
        DayOfWeek.dayOfWeek result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DayOfWeek.dayOfWeek buildPartial() {
        DayOfWeek.dayOfWeek result = new DayOfWeek.dayOfWeek(this);
        result.dayOfWeek_ = dayOfWeek_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DayOfWeek.dayOfWeek) {
          return mergeFrom((DayOfWeek.dayOfWeek)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DayOfWeek.dayOfWeek other) {
        if (other == DayOfWeek.dayOfWeek.getDefaultInstance()) return this;
        if (other.dayOfWeek_ != 0) {
          setDayOfWeekValue(other.getDayOfWeekValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DayOfWeek.dayOfWeek parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DayOfWeek.dayOfWeek) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dayOfWeek_ = 0;
      /**
       * <code>.dayOfWeek.Day day_of_Week = 1;</code>
       */
      public int getDayOfWeekValue() {
        return dayOfWeek_;
      }
      /**
       * <code>.dayOfWeek.Day day_of_Week = 1;</code>
       */
      public Builder setDayOfWeekValue(int value) {
        dayOfWeek_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dayOfWeek.Day day_of_Week = 1;</code>
       */
      public DayOfWeek.dayOfWeek.Day getDayOfWeek() {
        DayOfWeek.dayOfWeek.Day result = DayOfWeek.dayOfWeek.Day.valueOf(dayOfWeek_);
        return result == null ? DayOfWeek.dayOfWeek.Day.UNRECOGNIZED : result;
      }
      /**
       * <code>.dayOfWeek.Day day_of_Week = 1;</code>
       */
      public Builder setDayOfWeek(DayOfWeek.dayOfWeek.Day value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dayOfWeek_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dayOfWeek.Day day_of_Week = 1;</code>
       */
      public Builder clearDayOfWeek() {
        
        dayOfWeek_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dayOfWeek)
    }

    // @@protoc_insertion_point(class_scope:dayOfWeek)
    private static final DayOfWeek.dayOfWeek DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DayOfWeek.dayOfWeek();
    }

    public static DayOfWeek.dayOfWeek getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<dayOfWeek>
        PARSER = new com.google.protobuf.AbstractParser<dayOfWeek>() {
      public dayOfWeek parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dayOfWeek(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<dayOfWeek> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<dayOfWeek> getParserForType() {
      return PARSER;
    }

    public DayOfWeek.dayOfWeek getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dayOfWeek_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dayOfWeek_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017dayOfWeek.proto\"\242\001\n\tdayOfWeek\022#\n\013day_o" +
      "f_Week\030\001 \001(\0162\016.dayOfWeek.Day\"p\n\003Day\022\r\n\tU" +
      "NDEFINED\020\000\022\n\n\006MONDAY\020\001\022\013\n\007TUESDAY\020\002\022\r\n\tW" +
      "EDNESDAY\020\003\022\014\n\010THURSDAY\020\004\022\n\n\006FRIDAY\020\005\022\014\n\010" +
      "SATURDAY\020\006\022\n\n\006SUNDAY\020\007b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dayOfWeek_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dayOfWeek_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dayOfWeek_descriptor,
        new java.lang.String[] { "DayOfWeek", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
